/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewIndexRouteImport } from './routes/_authenticated/review/index'
import { Route as AuthenticatedNeedsWorkIndexRouteImport } from './routes/_authenticated/needs-work/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedCaptureIndexRouteImport } from './routes/_authenticated/capture/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsMarketplacesRouteImport } from './routes/_authenticated/settings/marketplaces'
import { Route as AuthenticatedSettingsHistoryRouteImport } from './routes/_authenticated/settings/history'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedCaptureIdRouteImport } from './routes/_authenticated/capture/$id'
import { Route as AuthenticatedAdminToolDebuggerRouteImport } from './routes/_authenticated/admin/tool-debugger'
import { Route as AuthenticatedAdminSettingsAuditRouteImport } from './routes/_authenticated/admin/settings-audit'
import { Route as AuthenticatedAdminMarketplaceAccountsRouteImport } from './routes/_authenticated/admin/marketplace-accounts'
import { Route as AuthenticatedAdminLearningRouteImport } from './routes/_authenticated/admin/learning'
import { Route as AuthenticatedItemsIdIndexRouteImport } from './routes/_authenticated/items/$id/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminOrgsIndexRouteImport } from './routes/_authenticated/admin/orgs/index'
import { Route as AuthenticatedAdminDomainExpertiseIndexRouteImport } from './routes/_authenticated/admin/domain-expertise/index'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as AuthenticatedAdminOrgsIdRouteImport } from './routes/_authenticated/admin/orgs/$id'
import { Route as AuthenticatedAdminDomainExpertiseModuleIdRouteImport } from './routes/_authenticated/admin/domain-expertise/$moduleId'
import { Route as AuthenticatedItemsIdResearchRunIdRouteImport } from './routes/_authenticated/items/$id/research/$runId'
import { Route as AuthenticatedAdminDomainExpertiseLookupTablesTableIdRouteImport } from './routes/_authenticated/admin/domain-expertise/lookup-tables/$tableId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewIndexRoute =
  AuthenticatedReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNeedsWorkIndexRoute =
  AuthenticatedNeedsWorkIndexRouteImport.update({
    id: '/needs-work/',
    path: '/needs-work/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureIndexRoute =
  AuthenticatedCaptureIndexRouteImport.update({
    id: '/capture/',
    path: '/capture/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMarketplacesRoute =
  AuthenticatedSettingsMarketplacesRouteImport.update({
    id: '/settings/marketplaces',
    path: '/settings/marketplaces',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHistoryRoute =
  AuthenticatedSettingsHistoryRouteImport.update({
    id: '/settings/history',
    path: '/settings/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureIdRoute = AuthenticatedCaptureIdRouteImport.update({
  id: '/capture/$id',
  path: '/capture/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminToolDebuggerRoute =
  AuthenticatedAdminToolDebuggerRouteImport.update({
    id: '/admin/tool-debugger',
    path: '/admin/tool-debugger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsAuditRoute =
  AuthenticatedAdminSettingsAuditRouteImport.update({
    id: '/admin/settings-audit',
    path: '/admin/settings-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMarketplaceAccountsRoute =
  AuthenticatedAdminMarketplaceAccountsRouteImport.update({
    id: '/admin/marketplace-accounts',
    path: '/admin/marketplace-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLearningRoute =
  AuthenticatedAdminLearningRouteImport.update({
    id: '/admin/learning',
    path: '/admin/learning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIdIndexRoute =
  AuthenticatedItemsIdIndexRouteImport.update({
    id: '/items/$id/',
    path: '/items/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrgsIndexRoute =
  AuthenticatedAdminOrgsIndexRouteImport.update({
    id: '/admin/orgs/',
    path: '/admin/orgs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDomainExpertiseIndexRoute =
  AuthenticatedAdminDomainExpertiseIndexRouteImport.update({
    id: '/admin/domain-expertise/',
    path: '/admin/domain-expertise/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrgsIdRoute =
  AuthenticatedAdminOrgsIdRouteImport.update({
    id: '/admin/orgs/$id',
    path: '/admin/orgs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDomainExpertiseModuleIdRoute =
  AuthenticatedAdminDomainExpertiseModuleIdRouteImport.update({
    id: '/admin/domain-expertise/$moduleId',
    path: '/admin/domain-expertise/$moduleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIdResearchRunIdRoute =
  AuthenticatedItemsIdResearchRunIdRouteImport.update({
    id: '/items/$id/research/$runId',
    path: '/items/$id/research/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute =
  AuthenticatedAdminDomainExpertiseLookupTablesTableIdRouteImport.update({
    id: '/admin/domain-expertise/lookup-tables/$tableId',
    path: '/admin/domain-expertise/lookup-tables/$tableId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/admin/settings-audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/admin/tool-debugger': typeof AuthenticatedAdminToolDebuggerRoute
  '/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/settings/history': typeof AuthenticatedSettingsHistoryRoute
  '/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/capture': typeof AuthenticatedCaptureIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/needs-work': typeof AuthenticatedNeedsWorkIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/domain-expertise/$moduleId': typeof AuthenticatedAdminDomainExpertiseModuleIdRoute
  '/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/domain-expertise': typeof AuthenticatedAdminDomainExpertiseIndexRoute
  '/admin/orgs': typeof AuthenticatedAdminOrgsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/items/$id': typeof AuthenticatedItemsIdIndexRoute
  '/admin/domain-expertise/lookup-tables/$tableId': typeof AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute
  '/items/$id/research/$runId': typeof AuthenticatedItemsIdResearchRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/admin/settings-audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/admin/tool-debugger': typeof AuthenticatedAdminToolDebuggerRoute
  '/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/settings/history': typeof AuthenticatedSettingsHistoryRoute
  '/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/capture': typeof AuthenticatedCaptureIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/needs-work': typeof AuthenticatedNeedsWorkIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/domain-expertise/$moduleId': typeof AuthenticatedAdminDomainExpertiseModuleIdRoute
  '/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/admin/domain-expertise': typeof AuthenticatedAdminDomainExpertiseIndexRoute
  '/admin/orgs': typeof AuthenticatedAdminOrgsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/items/$id': typeof AuthenticatedItemsIdIndexRoute
  '/admin/domain-expertise/lookup-tables/$tableId': typeof AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute
  '/items/$id/research/$runId': typeof AuthenticatedItemsIdResearchRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/learning': typeof AuthenticatedAdminLearningRoute
  '/_authenticated/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/_authenticated/admin/settings-audit': typeof AuthenticatedAdminSettingsAuditRoute
  '/_authenticated/admin/tool-debugger': typeof AuthenticatedAdminToolDebuggerRoute
  '/_authenticated/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/settings/history': typeof AuthenticatedSettingsHistoryRoute
  '/_authenticated/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/capture/': typeof AuthenticatedCaptureIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/needs-work/': typeof AuthenticatedNeedsWorkIndexRoute
  '/_authenticated/review/': typeof AuthenticatedReviewIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/admin/domain-expertise/$moduleId': typeof AuthenticatedAdminDomainExpertiseModuleIdRoute
  '/_authenticated/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/admin/domain-expertise/': typeof AuthenticatedAdminDomainExpertiseIndexRoute
  '/_authenticated/admin/orgs/': typeof AuthenticatedAdminOrgsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/items/$id/': typeof AuthenticatedItemsIdIndexRoute
  '/_authenticated/admin/domain-expertise/lookup-tables/$tableId': typeof AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute
  '/_authenticated/items/$id/research/$runId': typeof AuthenticatedItemsIdResearchRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/admin/learning'
    | '/admin/marketplace-accounts'
    | '/admin/settings-audit'
    | '/admin/tool-debugger'
    | '/capture/$id'
    | '/items/new'
    | '/settings/history'
    | '/settings/marketplaces'
    | '/settings/organization'
    | '/admin'
    | '/capture'
    | '/items'
    | '/needs-work'
    | '/review'
    | '/settings'
    | '/admin/domain-expertise/$moduleId'
    | '/admin/orgs/$id'
    | '/admin/users/$id'
    | '/admin/domain-expertise'
    | '/admin/orgs'
    | '/admin/users'
    | '/items/$id'
    | '/admin/domain-expertise/lookup-tables/$tableId'
    | '/items/$id/research/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/admin/learning'
    | '/admin/marketplace-accounts'
    | '/admin/settings-audit'
    | '/admin/tool-debugger'
    | '/capture/$id'
    | '/items/new'
    | '/settings/history'
    | '/settings/marketplaces'
    | '/settings/organization'
    | '/admin'
    | '/capture'
    | '/items'
    | '/needs-work'
    | '/review'
    | '/settings'
    | '/admin/domain-expertise/$moduleId'
    | '/admin/orgs/$id'
    | '/admin/users/$id'
    | '/admin/domain-expertise'
    | '/admin/orgs'
    | '/admin/users'
    | '/items/$id'
    | '/admin/domain-expertise/lookup-tables/$tableId'
    | '/items/$id/research/$runId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/admin/learning'
    | '/_authenticated/admin/marketplace-accounts'
    | '/_authenticated/admin/settings-audit'
    | '/_authenticated/admin/tool-debugger'
    | '/_authenticated/capture/$id'
    | '/_authenticated/items/new'
    | '/_authenticated/settings/history'
    | '/_authenticated/settings/marketplaces'
    | '/_authenticated/settings/organization'
    | '/_authenticated/admin/'
    | '/_authenticated/capture/'
    | '/_authenticated/items/'
    | '/_authenticated/needs-work/'
    | '/_authenticated/review/'
    | '/_authenticated/settings/'
    | '/_authenticated/admin/domain-expertise/$moduleId'
    | '/_authenticated/admin/orgs/$id'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/admin/domain-expertise/'
    | '/_authenticated/admin/orgs/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/items/$id/'
    | '/_authenticated/admin/domain-expertise/lookup-tables/$tableId'
    | '/_authenticated/items/$id/research/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review/': {
      id: '/_authenticated/review/'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/needs-work/': {
      id: '/_authenticated/needs-work/'
      path: '/needs-work'
      fullPath: '/needs-work'
      preLoaderRoute: typeof AuthenticatedNeedsWorkIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture/': {
      id: '/_authenticated/capture/'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/marketplaces': {
      id: '/_authenticated/settings/marketplaces'
      path: '/settings/marketplaces'
      fullPath: '/settings/marketplaces'
      preLoaderRoute: typeof AuthenticatedSettingsMarketplacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/history': {
      id: '/_authenticated/settings/history'
      path: '/settings/history'
      fullPath: '/settings/history'
      preLoaderRoute: typeof AuthenticatedSettingsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture/$id': {
      id: '/_authenticated/capture/$id'
      path: '/capture/$id'
      fullPath: '/capture/$id'
      preLoaderRoute: typeof AuthenticatedCaptureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tool-debugger': {
      id: '/_authenticated/admin/tool-debugger'
      path: '/admin/tool-debugger'
      fullPath: '/admin/tool-debugger'
      preLoaderRoute: typeof AuthenticatedAdminToolDebuggerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings-audit': {
      id: '/_authenticated/admin/settings-audit'
      path: '/admin/settings-audit'
      fullPath: '/admin/settings-audit'
      preLoaderRoute: typeof AuthenticatedAdminSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/marketplace-accounts': {
      id: '/_authenticated/admin/marketplace-accounts'
      path: '/admin/marketplace-accounts'
      fullPath: '/admin/marketplace-accounts'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/learning': {
      id: '/_authenticated/admin/learning'
      path: '/admin/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AuthenticatedAdminLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$id/': {
      id: '/_authenticated/items/$id/'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthenticatedItemsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/orgs/': {
      id: '/_authenticated/admin/orgs/'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AuthenticatedAdminOrgsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/domain-expertise/': {
      id: '/_authenticated/admin/domain-expertise/'
      path: '/admin/domain-expertise'
      fullPath: '/admin/domain-expertise'
      preLoaderRoute: typeof AuthenticatedAdminDomainExpertiseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/orgs/$id': {
      id: '/_authenticated/admin/orgs/$id'
      path: '/admin/orgs/$id'
      fullPath: '/admin/orgs/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrgsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/domain-expertise/$moduleId': {
      id: '/_authenticated/admin/domain-expertise/$moduleId'
      path: '/admin/domain-expertise/$moduleId'
      fullPath: '/admin/domain-expertise/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminDomainExpertiseModuleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$id/research/$runId': {
      id: '/_authenticated/items/$id/research/$runId'
      path: '/items/$id/research/$runId'
      fullPath: '/items/$id/research/$runId'
      preLoaderRoute: typeof AuthenticatedItemsIdResearchRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/domain-expertise/lookup-tables/$tableId': {
      id: '/_authenticated/admin/domain-expertise/lookup-tables/$tableId'
      path: '/admin/domain-expertise/lookup-tables/$tableId'
      fullPath: '/admin/domain-expertise/lookup-tables/$tableId'
      preLoaderRoute: typeof AuthenticatedAdminDomainExpertiseLookupTablesTableIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminLearningRoute: typeof AuthenticatedAdminLearningRoute
  AuthenticatedAdminMarketplaceAccountsRoute: typeof AuthenticatedAdminMarketplaceAccountsRoute
  AuthenticatedAdminSettingsAuditRoute: typeof AuthenticatedAdminSettingsAuditRoute
  AuthenticatedAdminToolDebuggerRoute: typeof AuthenticatedAdminToolDebuggerRoute
  AuthenticatedCaptureIdRoute: typeof AuthenticatedCaptureIdRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedSettingsHistoryRoute: typeof AuthenticatedSettingsHistoryRoute
  AuthenticatedSettingsMarketplacesRoute: typeof AuthenticatedSettingsMarketplacesRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCaptureIndexRoute: typeof AuthenticatedCaptureIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedNeedsWorkIndexRoute: typeof AuthenticatedNeedsWorkIndexRoute
  AuthenticatedReviewIndexRoute: typeof AuthenticatedReviewIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedAdminDomainExpertiseModuleIdRoute: typeof AuthenticatedAdminDomainExpertiseModuleIdRoute
  AuthenticatedAdminOrgsIdRoute: typeof AuthenticatedAdminOrgsIdRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminDomainExpertiseIndexRoute: typeof AuthenticatedAdminDomainExpertiseIndexRoute
  AuthenticatedAdminOrgsIndexRoute: typeof AuthenticatedAdminOrgsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedItemsIdIndexRoute: typeof AuthenticatedItemsIdIndexRoute
  AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute: typeof AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute
  AuthenticatedItemsIdResearchRunIdRoute: typeof AuthenticatedItemsIdResearchRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminLearningRoute: AuthenticatedAdminLearningRoute,
  AuthenticatedAdminMarketplaceAccountsRoute:
    AuthenticatedAdminMarketplaceAccountsRoute,
  AuthenticatedAdminSettingsAuditRoute: AuthenticatedAdminSettingsAuditRoute,
  AuthenticatedAdminToolDebuggerRoute: AuthenticatedAdminToolDebuggerRoute,
  AuthenticatedCaptureIdRoute: AuthenticatedCaptureIdRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedSettingsHistoryRoute: AuthenticatedSettingsHistoryRoute,
  AuthenticatedSettingsMarketplacesRoute:
    AuthenticatedSettingsMarketplacesRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCaptureIndexRoute: AuthenticatedCaptureIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedNeedsWorkIndexRoute: AuthenticatedNeedsWorkIndexRoute,
  AuthenticatedReviewIndexRoute: AuthenticatedReviewIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedAdminDomainExpertiseModuleIdRoute:
    AuthenticatedAdminDomainExpertiseModuleIdRoute,
  AuthenticatedAdminOrgsIdRoute: AuthenticatedAdminOrgsIdRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminDomainExpertiseIndexRoute:
    AuthenticatedAdminDomainExpertiseIndexRoute,
  AuthenticatedAdminOrgsIndexRoute: AuthenticatedAdminOrgsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedItemsIdIndexRoute: AuthenticatedItemsIdIndexRoute,
  AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute:
    AuthenticatedAdminDomainExpertiseLookupTablesTableIdRoute,
  AuthenticatedItemsIdResearchRunIdRoute:
    AuthenticatedItemsIdResearchRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
