/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewIndexRouteImport } from './routes/_authenticated/review/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedCaptureIndexRouteImport } from './routes/_authenticated/capture/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsMarketplacesRouteImport } from './routes/_authenticated/settings/marketplaces'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedItemsIdRouteImport } from './routes/_authenticated/items/$id'
import { Route as AuthenticatedCaptureIdRouteImport } from './routes/_authenticated/capture/$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminOrgsRouteImport } from './routes/_authenticated/admin/orgs'
import { Route as AuthenticatedAdminMarketplaceAccountsRouteImport } from './routes/_authenticated/admin/marketplace-accounts'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as AuthenticatedAdminOrgsIdRouteImport } from './routes/_authenticated/admin/orgs.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewIndexRoute =
  AuthenticatedReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureIndexRoute =
  AuthenticatedCaptureIndexRouteImport.update({
    id: '/capture/',
    path: '/capture/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsMarketplacesRoute =
  AuthenticatedSettingsMarketplacesRouteImport.update({
    id: '/settings/marketplaces',
    path: '/settings/marketplaces',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsIdRoute = AuthenticatedItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureIdRoute = AuthenticatedCaptureIdRouteImport.update({
  id: '/capture/$id',
  path: '/capture/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminOrgsRoute = AuthenticatedAdminOrgsRouteImport.update({
  id: '/admin/orgs',
  path: '/admin/orgs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMarketplaceAccountsRoute =
  AuthenticatedAdminMarketplaceAccountsRouteImport.update({
    id: '/admin/marketplace-accounts',
    path: '/admin/marketplace-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminOrgsIdRoute =
  AuthenticatedAdminOrgsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrgsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/admin/orgs': typeof AuthenticatedAdminOrgsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/capture': typeof AuthenticatedCaptureIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/admin/orgs': typeof AuthenticatedAdminOrgsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/capture': typeof AuthenticatedCaptureIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/marketplace-accounts': typeof AuthenticatedAdminMarketplaceAccountsRoute
  '/_authenticated/admin/orgs': typeof AuthenticatedAdminOrgsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/capture/$id': typeof AuthenticatedCaptureIdRoute
  '/_authenticated/items/$id': typeof AuthenticatedItemsIdRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/settings/marketplaces': typeof AuthenticatedSettingsMarketplacesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/capture/': typeof AuthenticatedCaptureIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/review/': typeof AuthenticatedReviewIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/admin/orgs/$id': typeof AuthenticatedAdminOrgsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/admin/marketplace-accounts'
    | '/admin/orgs'
    | '/admin/users'
    | '/capture/$id'
    | '/items/$id'
    | '/items/new'
    | '/settings/marketplaces'
    | '/admin'
    | '/capture'
    | '/items'
    | '/review'
    | '/settings'
    | '/admin/orgs/$id'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/admin/marketplace-accounts'
    | '/admin/orgs'
    | '/admin/users'
    | '/capture/$id'
    | '/items/$id'
    | '/items/new'
    | '/settings/marketplaces'
    | '/admin'
    | '/capture'
    | '/items'
    | '/review'
    | '/settings'
    | '/admin/orgs/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/'
    | '/_authenticated/admin/marketplace-accounts'
    | '/_authenticated/admin/orgs'
    | '/_authenticated/admin/users'
    | '/_authenticated/capture/$id'
    | '/_authenticated/items/$id'
    | '/_authenticated/items/new'
    | '/_authenticated/settings/marketplaces'
    | '/_authenticated/admin/'
    | '/_authenticated/capture/'
    | '/_authenticated/items/'
    | '/_authenticated/review/'
    | '/_authenticated/settings/'
    | '/_authenticated/admin/orgs/$id'
    | '/_authenticated/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review/': {
      id: '/_authenticated/review/'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture/': {
      id: '/_authenticated/capture/'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/marketplaces': {
      id: '/_authenticated/settings/marketplaces'
      path: '/settings/marketplaces'
      fullPath: '/settings/marketplaces'
      preLoaderRoute: typeof AuthenticatedSettingsMarketplacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$id': {
      id: '/_authenticated/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthenticatedItemsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture/$id': {
      id: '/_authenticated/capture/$id'
      path: '/capture/$id'
      fullPath: '/capture/$id'
      preLoaderRoute: typeof AuthenticatedCaptureIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/orgs': {
      id: '/_authenticated/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AuthenticatedAdminOrgsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/marketplace-accounts': {
      id: '/_authenticated/admin/marketplace-accounts'
      path: '/admin/marketplace-accounts'
      fullPath: '/admin/marketplace-accounts'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/orgs/$id': {
      id: '/_authenticated/admin/orgs/$id'
      path: '/$id'
      fullPath: '/admin/orgs/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrgsIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrgsRoute
    }
  }
}

interface AuthenticatedAdminOrgsRouteChildren {
  AuthenticatedAdminOrgsIdRoute: typeof AuthenticatedAdminOrgsIdRoute
}

const AuthenticatedAdminOrgsRouteChildren: AuthenticatedAdminOrgsRouteChildren =
  {
    AuthenticatedAdminOrgsIdRoute: AuthenticatedAdminOrgsIdRoute,
  }

const AuthenticatedAdminOrgsRouteWithChildren =
  AuthenticatedAdminOrgsRoute._addFileChildren(
    AuthenticatedAdminOrgsRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminMarketplaceAccountsRoute: typeof AuthenticatedAdminMarketplaceAccountsRoute
  AuthenticatedAdminOrgsRoute: typeof AuthenticatedAdminOrgsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedCaptureIdRoute: typeof AuthenticatedCaptureIdRoute
  AuthenticatedItemsIdRoute: typeof AuthenticatedItemsIdRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedSettingsMarketplacesRoute: typeof AuthenticatedSettingsMarketplacesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCaptureIndexRoute: typeof AuthenticatedCaptureIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedReviewIndexRoute: typeof AuthenticatedReviewIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminMarketplaceAccountsRoute:
    AuthenticatedAdminMarketplaceAccountsRoute,
  AuthenticatedAdminOrgsRoute: AuthenticatedAdminOrgsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedCaptureIdRoute: AuthenticatedCaptureIdRoute,
  AuthenticatedItemsIdRoute: AuthenticatedItemsIdRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedSettingsMarketplacesRoute:
    AuthenticatedSettingsMarketplacesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCaptureIndexRoute: AuthenticatedCaptureIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedReviewIndexRoute: AuthenticatedReviewIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
