name: 'Docker Build and Push to ECR'
description: 'Build a Docker image and push to Amazon ECR with caching'

inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  image-name:
    description: 'ECR repository name (e.g., listforge-api)'
    required: true
  ecr-registry:
    description: 'ECR registry URL'
    required: true
  build-args:
    description: 'Docker build arguments (newline separated KEY=VALUE)'
    required: false
    default: ''
  context:
    description: 'Docker build context'
    required: false
    default: '.'

outputs:
  image-uri:
    description: 'Full image URI with SHA tag'
    value: ${{ steps.build.outputs.image-uri }}
  image-uri-latest:
    description: 'Full image URI with latest tag'
    value: ${{ steps.build.outputs.image-uri-latest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: build
      shell: bash
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
        IMAGE_NAME: ${{ inputs.image-name }}
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        BUILD_ARGS: ${{ inputs.build-args }}
        CONTEXT: ${{ inputs.context }}
        SHA: ${{ github.sha }}
      run: |
        IMAGE_URI="${ECR_REGISTRY}/${IMAGE_NAME}:${SHA}"
        IMAGE_URI_LATEST="${ECR_REGISTRY}/${IMAGE_NAME}:latest"
        
        echo "Building ${IMAGE_URI}..."
        
        # Build build-args string
        BUILD_ARGS_FLAGS=""
        if [ -n "$BUILD_ARGS" ]; then
          while IFS= read -r arg; do
            if [ -n "$arg" ]; then
              BUILD_ARGS_FLAGS="${BUILD_ARGS_FLAGS} --build-arg ${arg}"
            fi
          done <<< "$BUILD_ARGS"
        fi
        
        # Build with cache
        docker buildx build \
          --file "${DOCKERFILE}" \
          --tag "${IMAGE_URI}" \
          --tag "${IMAGE_URI_LATEST}" \
          --cache-from "type=gha,scope=${IMAGE_NAME}" \
          --cache-to "type=gha,mode=max,scope=${IMAGE_NAME}" \
          --push \
          ${BUILD_ARGS_FLAGS} \
          "${CONTEXT}"
        
        echo "image-uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
        echo "image-uri-latest=${IMAGE_URI_LATEST}" >> $GITHUB_OUTPUT
        
        echo "✅ Pushed ${IMAGE_URI}"
        echo "✅ Pushed ${IMAGE_URI_LATEST}"

